[package]
name = "composite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlparser = { path = "../sqlparser-rs" }
snafu = "0.7.3"
lazy_static = "1.4.0"
